from .auth import AuthErr

AuthErr = AuthErr()
